CREATE TABLE "mytable" (
  "CREATE DATABASE safebank;" text
);

INSERT INTO "mytable" ("CREATE DATABASE safebank;")
VALUES
('USE safebank;'),
('-- ======================='),
('-- Tabela de Usuários'),
('-- ======================='),
('CREATE TABLE usuarios ('),
('id_usuario INT AUTO_INCREMENT PRIMARY KEY'),
('nome VARCHAR(100) NOT NULL'),
('email VARCHAR(100) NOT NULL UNIQUE'),
('senha VARCHAR(100) NOT NULL'),
('cidade VARCHAR(50)'),
('idade INT'),
(');'),
('-- ======================='),
('-- Tabela de Golpes'),
('-- ======================='),
('CREATE TABLE golpes ('),
('id_golpe INT AUTO_INCREMENT PRIMARY KEY'),
('tipo VARCHAR(50) NOT NULL'),
('descricao TEXT NOT NULL'),
('data_ocorrencia DATE'),
('banco_relacionado VARCHAR(100)'),
('id_usuario INT'),
('FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)'),
(');'),
('-- ======================='),
('-- Tabela de Dicas de Segurança'),
('-- ======================='),
('CREATE TABLE dicas ('),
('id_dica INT AUTO_INCREMENT PRIMARY KEY'),
('tipo_golpe VARCHAR(50) NOT NULL'),
('mensagem TEXT NOT NULL'),
(');'),
('-- ======================='),
('-- Inserindo algumas dicas padrão'),
('-- ======================='),
('INSERT INTO dicas (tipo_golpe'),
('(''Ligação falsa'''),
('(''E-mail fraudulento'''),
('(''WhatsApp'''),
('(''Link suspeito'''),
('(''Outros''');
